version: 0.0
os: windows
files:
  - source: /
    destination: C:\Websites\BitbucketAWSTest
hooks:
  BeforeInstall:
    - location: \before-iis-install-stop.bat
      timeout: 900
  AfterInstall:
    - location: \after-iis-install-start.bat
      timeout: 180
